# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: endereco.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="endereco.proto",
    package="endereco",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0e\x65ndereco.proto\x12\x08\x65ndereco"g\n\x08\x45ndereco\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nlogradouro\x18\x02 \x01(\t\x12\x0b\n\x03\x63\x65p\x18\x03 \x01(\t\x12\x0e\n\x06\x62\x61irro\x18\x04 \x01(\t\x12\x0e\n\x06\x63idade\x18\x05 \x01(\t\x12\x0e\n\x06\x65stado\x18\x06 \x01(\t" \n\x0e\x44\x65leteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x9d\x02\n\x0f\x45nderecoService\x12\x32\n\x06\x43reate\x12\x12.endereco.Endereco\x1a\x12.endereco.Endereco"\x00\x12\x32\n\x04List\x12\x12.endereco.Endereco\x1a\x12.endereco.Endereco"\x00\x30\x01\x12\x34\n\x08Retrieve\x12\x12.endereco.Endereco\x1a\x12.endereco.Endereco"\x00\x12\x32\n\x06Update\x12\x12.endereco.Endereco\x1a\x12.endereco.Endereco"\x00\x12\x38\n\x06\x44\x65lete\x12\x12.endereco.Endereco\x1a\x18.endereco.DeleteResponse"\x00\x62\x06proto3',
)


_ENDERECO = _descriptor.Descriptor(
    name="Endereco",
    full_name="endereco.Endereco",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="endereco.Endereco.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="logradouro",
            full_name="endereco.Endereco.logradouro",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="cep",
            full_name="endereco.Endereco.cep",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="bairro",
            full_name="endereco.Endereco.bairro",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="cidade",
            full_name="endereco.Endereco.cidade",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="estado",
            full_name="endereco.Endereco.estado",
            index=5,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=28,
    serialized_end=131,
)


_DELETERESPONSE = _descriptor.Descriptor(
    name="DeleteResponse",
    full_name="endereco.DeleteResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="status",
            full_name="endereco.DeleteResponse.status",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=133,
    serialized_end=165,
)

DESCRIPTOR.message_types_by_name["Endereco"] = _ENDERECO
DESCRIPTOR.message_types_by_name["DeleteResponse"] = _DELETERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Endereco = _reflection.GeneratedProtocolMessageType(
    "Endereco",
    (_message.Message,),
    {
        "DESCRIPTOR": _ENDERECO,
        "__module__": "endereco_pb2"
        # @@protoc_insertion_point(class_scope:endereco.Endereco)
    },
)
_sym_db.RegisterMessage(Endereco)

DeleteResponse = _reflection.GeneratedProtocolMessageType(
    "DeleteResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _DELETERESPONSE,
        "__module__": "endereco_pb2"
        # @@protoc_insertion_point(class_scope:endereco.DeleteResponse)
    },
)
_sym_db.RegisterMessage(DeleteResponse)


_ENDERECOSERVICE = _descriptor.ServiceDescriptor(
    name="EnderecoService",
    full_name="endereco.EnderecoService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=168,
    serialized_end=453,
    methods=[
        _descriptor.MethodDescriptor(
            name="Create",
            full_name="endereco.EnderecoService.Create",
            index=0,
            containing_service=None,
            input_type=_ENDERECO,
            output_type=_ENDERECO,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="List",
            full_name="endereco.EnderecoService.List",
            index=1,
            containing_service=None,
            input_type=_ENDERECO,
            output_type=_ENDERECO,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Retrieve",
            full_name="endereco.EnderecoService.Retrieve",
            index=2,
            containing_service=None,
            input_type=_ENDERECO,
            output_type=_ENDERECO,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Update",
            full_name="endereco.EnderecoService.Update",
            index=3,
            containing_service=None,
            input_type=_ENDERECO,
            output_type=_ENDERECO,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Delete",
            full_name="endereco.EnderecoService.Delete",
            index=4,
            containing_service=None,
            input_type=_ENDERECO,
            output_type=_DELETERESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_ENDERECOSERVICE)

DESCRIPTOR.services_by_name["EnderecoService"] = _ENDERECOSERVICE

# @@protoc_insertion_point(module_scope)
