# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cliente_pb2 as cliente__pb2


class ClienteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/cliente.ClienteService/Create',
                request_serializer=cliente__pb2.Cliente.SerializeToString,
                response_deserializer=cliente__pb2.Cliente.FromString,
                )
        self.List = channel.unary_stream(
                '/cliente.ClienteService/List',
                request_serializer=cliente__pb2.Cliente.SerializeToString,
                response_deserializer=cliente__pb2.Cliente.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/cliente.ClienteService/Retrieve',
                request_serializer=cliente__pb2.Cliente.SerializeToString,
                response_deserializer=cliente__pb2.Cliente.FromString,
                )
        self.Update = channel.unary_unary(
                '/cliente.ClienteService/Update',
                request_serializer=cliente__pb2.Cliente.SerializeToString,
                response_deserializer=cliente__pb2.Cliente.FromString,
                )
        self.Delete = channel.unary_unary(
                '/cliente.ClienteService/Delete',
                request_serializer=cliente__pb2.Cliente.SerializeToString,
                response_deserializer=cliente__pb2.DeleteResponse.FromString,
                )


class ClienteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClienteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=cliente__pb2.Cliente.FromString,
                    response_serializer=cliente__pb2.Cliente.SerializeToString,
            ),
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=cliente__pb2.Cliente.FromString,
                    response_serializer=cliente__pb2.Cliente.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=cliente__pb2.Cliente.FromString,
                    response_serializer=cliente__pb2.Cliente.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=cliente__pb2.Cliente.FromString,
                    response_serializer=cliente__pb2.Cliente.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=cliente__pb2.Cliente.FromString,
                    response_serializer=cliente__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cliente.ClienteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClienteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cliente.ClienteService/Create',
            cliente__pb2.Cliente.SerializeToString,
            cliente__pb2.Cliente.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cliente.ClienteService/List',
            cliente__pb2.Cliente.SerializeToString,
            cliente__pb2.Cliente.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cliente.ClienteService/Retrieve',
            cliente__pb2.Cliente.SerializeToString,
            cliente__pb2.Cliente.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cliente.ClienteService/Update',
            cliente__pb2.Cliente.SerializeToString,
            cliente__pb2.Cliente.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cliente.ClienteService/Delete',
            cliente__pb2.Cliente.SerializeToString,
            cliente__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
