# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import endereco_pb2 as endereco__pb2


class EnderecoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/endereco.EnderecoService/Create',
                request_serializer=endereco__pb2.Endereco.SerializeToString,
                response_deserializer=endereco__pb2.Endereco.FromString,
                )
        self.List = channel.unary_stream(
                '/endereco.EnderecoService/List',
                request_serializer=endereco__pb2.Endereco.SerializeToString,
                response_deserializer=endereco__pb2.Endereco.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/endereco.EnderecoService/Retrieve',
                request_serializer=endereco__pb2.Endereco.SerializeToString,
                response_deserializer=endereco__pb2.Endereco.FromString,
                )
        self.Update = channel.unary_unary(
                '/endereco.EnderecoService/Update',
                request_serializer=endereco__pb2.Endereco.SerializeToString,
                response_deserializer=endereco__pb2.Endereco.FromString,
                )
        self.Delete = channel.unary_unary(
                '/endereco.EnderecoService/Delete',
                request_serializer=endereco__pb2.Endereco.SerializeToString,
                response_deserializer=endereco__pb2.DeleteResponse.FromString,
                )


class EnderecoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnderecoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=endereco__pb2.Endereco.FromString,
                    response_serializer=endereco__pb2.Endereco.SerializeToString,
            ),
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=endereco__pb2.Endereco.FromString,
                    response_serializer=endereco__pb2.Endereco.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=endereco__pb2.Endereco.FromString,
                    response_serializer=endereco__pb2.Endereco.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=endereco__pb2.Endereco.FromString,
                    response_serializer=endereco__pb2.Endereco.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=endereco__pb2.Endereco.FromString,
                    response_serializer=endereco__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'endereco.EnderecoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EnderecoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endereco.EnderecoService/Create',
            endereco__pb2.Endereco.SerializeToString,
            endereco__pb2.Endereco.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/endereco.EnderecoService/List',
            endereco__pb2.Endereco.SerializeToString,
            endereco__pb2.Endereco.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endereco.EnderecoService/Retrieve',
            endereco__pb2.Endereco.SerializeToString,
            endereco__pb2.Endereco.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endereco.EnderecoService/Update',
            endereco__pb2.Endereco.SerializeToString,
            endereco__pb2.Endereco.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endereco.EnderecoService/Delete',
            endereco__pb2.Endereco.SerializeToString,
            endereco__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
